// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/truongle2004/campus_marketplace/internal/database"
	"github.com/truongle2004/campus_marketplace/internal/modules/campus"
	"github.com/truongle2004/campus_marketplace/internal/modules/category"
	"github.com/truongle2004/campus_marketplace/internal/modules/user"
	"github.com/truongle2004/campus_marketplace/pkg/auth"
	"github.com/truongle2004/campus_marketplace/pkg/logger"
	"net/http"
)

import (
	_ "github.com/truongle2004/campus_marketplace/docs"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	int2 := ProvidePort()
	db := database.NewDatabase()
	campusRepo := campus.NewRepo(db)
	campusService := campus.NewService(campusRepo)
	handler := campus.NewHandler(campusService)
	routes := campus.NewRoutes(handler)
	categoryRepo := category.NewRepo(db)
	categoryService := category.NewService(categoryRepo)
	categoryHandler := category.NewHandler(categoryService)
	categoryRoutes := category.NewRoutes(categoryHandler)
	userRepo := user.NewRepo(db)
	userService := user.NewService(userRepo, campusService)
	userHandler := user.NewHandler(userService)
	middleware, err := auth.NewMiddleware()
	if err != nil {
		return nil, err
	}
	userRoutes := user.NewRoutes(userHandler, middleware)
	httpHandler := NewHTTPHandler(routes, categoryRoutes, userRoutes)
	server := NewHTTPServer(int2, httpHandler)
	logger, err := ProvideLogger()
	if err != nil {
		return nil, err
	}
	app := &App{
		Server: server,
		Logger: logger,
	}
	return app, nil
}

// wire.go:

type App struct {
	Server *http.Server
	Logger *logger.Logger
}
