basePath: /
host: localhost:8080
info:
  contact: {}
  description: API server for Campus Marketplace
  title: Campus Marketplace API
  version: "1.0"
paths:
  /:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Hello world
      tags:
      - general
  /health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - general
swagger: "2.0"
